[package]
name = "fabric"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "daemon"
path = "src/bin/daemon.rs"

[[bin]]
name = "management"
path = "src/bin/management.rs"

[lib]
path = "src/lib.rs"

