[package]
name = "fabric"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.80"
sqlx = { version = "0.7.4", features = ["runtime-tokio-rustls", "sqlite"] }
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread", "time"] }
tonic = "0.11.0"
kafka = "0.10.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", features = ["env-filter"]}
rand = "0.8.5"
dotenv = "0.15.0"
prost = "0.12.6"
tonic-reflection = "0.11.0"
futures = "0.3.30"
k8s-openapi = { version = "0.22.0", features = ["latest"] }
kube = { version = "0.92.0", features = ["client"] }

[[bin]]
name = "daemon"
path = "src/bin/daemon.rs"

[[bin]]
name = "rpc"
path = "src/bin/rpc.rs"

[lib]
path = "src/lib.rs"

[dev-dependencies]
mockall = "0.12.1"

[build-dependencies]
tonic-build = "0.11.0"

[profile.dev.package.sqlx-macros]
opt-level = 3
