db_path="dev.backoffice.db"
topic="events"

[kafka_consumer]
"bootstrap.servers" = "localhost:19092"
"group.id"= "billing-stg-local-1"
"auto.offset.reset" = "earliest"
"enable.partition.eof" = true
"security.protocol" = "SASL_SSL"
"sasl.mechanisms" = "SCRAM-SHA-256"
"sasl.username" = ""
"sasl.password" = ""

[auth]
url = "https://txpipe.us.auth0.com"
client_id=""
client_secret=""
audience="https://txpipe.us.auth0.com/api/v2/"
