db_path="dev.backoffice.db"
topic="events"

[kafka_consumer]
"bootstrap.servers" = "localhost:19092"
"group.id"= "billing-stg-local-1"
"auto.offset.reset" = "earliest"
"enable.partition.eof" = true
"security.protocol" = "SASL_SSL"
"sasl.mechanisms" = "SCRAM-SHA-256"
"sasl.username" = ""
"sasl.password" = ""

[auth]
url = "https://txpipe.us.auth0.com"
client_id=""
client_secret=""
audience="https://txpipe.us.auth0.com/api/v2/"

[stripe]
url = "https://api.stripe.com/v1"
api_key = ""

# Only needed by invite-user
[email]
ses_access_key_id = "xxx"
ses_secret_access_key = "xxx"
ses_region = "us-west-2"
ses_verified_email = "no-reply@demeter.run"
