addr="0.0.0.0:5000"
db_path="dev.db"
crds_path="examples/crds"
secret="fabric@txpipe"
topic="events"
invite_ttl_min="15"

[kafka_producer]
"bootstrap.servers" = "localhost:19092"

[kafka_consumer]
"bootstrap.servers" = "localhost:19092"
"group.id"= "rpc"

[auth]
url="https://txpipe.us.auth0.com"
client_id=""
client_secret=""
audience=""

[stripe]
url = "https://api.stripe.com/v1"
api_key = ""
