FROM rust:1.79-slim-buster AS build

WORKDIR /app

RUN apt update 
RUN apt install -y build-essential pkg-config libssl-dev libsasl2-dev cmake

COPY ./Cargo.toml ./Cargo.toml
COPY . .

RUN cargo build --release --bin=rpc

FROM rust:1.79-slim-buster 

WORKDIR /fabric

RUN apt update 
RUN apt install -y build-essential pkg-config libssl-dev libsasl2-dev cmake

COPY --from=build /app/target/release/rpc .
COPY ./data ./data

CMD ["./rpc"]
LABEL service=rpc
