FROM rust:1.85-slim AS build

WORKDIR /app

RUN apt update 
RUN apt install -y build-essential pkg-config libssl-dev libsasl2-dev cmake

COPY ./Cargo.toml ./Cargo.toml
COPY . .

RUN cargo build --release --bin=daemon

FROM rust:1.85-slim 

RUN apt update 
RUN apt install -y libssl-dev libsasl2-dev

COPY --from=build /app/target/release/ ./

CMD ["./daemon"]
LABEL service=daemon
