name: Build

# on:
#   workflow_dispatch: {}
#   push:
#     branches:
#       - "main"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rpc:
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: .
            file: docker/dockerfile.rpc
            endpoint: demeter-run/fabric-rpc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ${{ matrix.context }}
      #     file: ${{ matrix.file }}
      #     platforms: linux/amd64
      #     push: true
      #     tags: ghcr.io/${{ matrix.endpoint }},ghcr.io/${{ matrix.endpoint }}:${{ github.sha }}
  daemon:
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: .
            file: docker/dockerfile.daemon
            endpoint: demeter-run/fabric-daemon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ${{ matrix.context }}
      #     file: ${{ matrix.file }}
      #     platforms: linux/amd64
      #     push: true
      #     tags: ghcr.io/${{ matrix.endpoint }},ghcr.io/${{ matrix.endpoint }}:${{ github.sha }}
