name: Clippy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Environment
        run: |
          cargo install --version=0.7.4 sql-cli
          cargo sqlx db create 
          cargo sqlx migrate run --source ./src/driven/cache/migrations

      - name: Clippy check lints
        run: cargo clippy -- -D warnings
