name: Test e2e 

on:
  schedule:
  - cron: "0 * * * *"

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Integration Tests
        env:
          PASSWORD: ${{ secrets.E2E_USER_PASSWORD }}
          CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
        run: ./test/e2e
      
