name: Release Backoffice CLI

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*.*.*"  

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [x86_64-unknown-linux-gnu, x86_64-apple-darwin]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.platform }}
          override: true

      - name: Install cargo-dist
        run: cargo install cargo-dist

      - name: Build with cargo-dist
        run: cargo dist build --bin cli --target ${{ matrix.platform }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.platform }}
          path: target/dist/${{ matrix.platform }}/*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-x86_64-unknown-linux-gnu
          path: dist/linux

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-x86_64-apple-darwin
          path: dist/mac

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Backoffice CLI Release ${{ github.ref_name }}
          artifacts: "dist/linux/*.tar.gz,dist/mac/*.tar.gz"

