name: Test 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Run Unit Tests 
        run: cargo test --lib 
